### ISSUE TITLE
Add time to Payload

### ISSUE THREAD

**Issue by slifty** [tvkitchen/base#34]
#### Description
We've finally figured out what time means, unlocking one of the deepest secrets of the universe. Amazing.

Now we just need to add that concept to our `Payload` class.

Since Payloads are going to contain lots of types of data, I want to break away from the MPEG-TS concepts of `PTS` and `DTS` and instead lets go with:

* `createdAt`: the UTC timestamp the payload was created.
* `streamTime`: the time offset of the Payload, relative to the start of a stream.
* `absoluteTime`: the estimated absolute time that the Payload's content reflects.
* `duration`: the amount of time covered by the content of a given Payload.

All times in terms of seconds (or should it be miliseconds)

#### Relevant Resources / Research
https://github.com/tvkitchen/tv-kitchen/issues/45
https://github.com/tvkitchen/tv-kitchen/issues/42

#### Related Issues
None in this repo.

**Comment by reefdog** [comment]
Okay handful of thoughts, banged out on Slack:

- `createdAt` is a fine name and universally-understood.
- `streamTime` could be `timeSinceStreamStart` or `offsetSinceStreamStart`. (I kind of like `offset` but it may be loaded.)
- `duration` is 👍
- `absoluteTime` we should hammer out the source of a bit more before naming, IMO, but my vote is for `interruptingCowstamp`
- I have a loose preference for milliseconds over seconds.
- I have a loose preference for timestamps to be expressed as ISO 8601 rather than Unix epoch time just because they're so much more human-readable, which is handy during inspections.

**Comment by slifty** [comment]
(Ah yeah, offset is loaded since kafka stream offsets are a thing.)

Locking in on:

* `createdAt` as ISO 8601 just so we can all be mad at @reefdog.
* `duration` in ms.
* `position` in ms.  Note: this is inspired by [twitch API](https://dev.twitch.tv/docs/api/reference/#get-streams) which has a field called `position_seconds` that marks the "Relative offset (in seconds) of the marker, from the beginning of the stream."
* `abs

Planning to hold off on `interruptingCowstamp` for right now, and add it in soon (until we add it, we won't be able to place a given caption in real time, just relative time from a stream or file), though I think `absoluteTimestamp` or even just `timestamp` might be the right name given the other names.

**Comment by reefdog** [comment]
I highly approve of all three bulleted suggestions, and of using `timestamp` for the `interruptingCowstamp` concept.

**Comment by slifty** [comment]
Another update:

Gonna go ahead and include `timestamp`

**Comment by reefdog** [comment]
MOO
